### ISSUE TITLE
Screenshots problem

### ISSUE THREAD

**Issue by cathywilkie** [cathywilkie/navigation-highlight#1]
Markbot gives me a high percentage of error for the screenshots when the difference between the pictures is really small.
I compared my code with others in my group and it was really similar.

@thomasjbradley

**Comment by thomasjbradley** [comment]
You could be running into the colour profile problem. Do the colours in the screenshot for your website look more muted than my screenshot?

If that’s the case, try downloading this new version of Markbot & see if it works:
https://assets.learn-the-web.algonquindesign.ca/markbot/Install%20Markbot.dmg

**Comment by cathywilkie** [comment]
It did indeed! I tested it and it worked, thank you! 
Should I get rid of Markbot 2 now?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, delete the older version.

**Comment by cathywilkie** [comment]
Awesome, thank you!
